### ISSUE TITLE
Requêtes spécifiques "Scope"

### ISSUE THREAD

**Issue by stevevisinand** [HE-Arc/Caravel#142]
`$group->usersRefused()`

me semble plus propre en

`$group->users()->refused()`

Le dev utilisant `refused` se rend plus facilement compte qu'il fait une requête supplémentaire en procédant ainsi.

Pour cela:  https://laravel.com/docs/8.x/eloquent#local-scopes

**Comment by M4n0x** [comment]
Fixé en #170
