### ISSUE TITLE
No redirect to desired page if logged out

### ISSUE THREAD

**Issue by Zegorax** [HE-Arc/Caravel#152]
# Description
If the user is logged out of the app try to refresh the page, the app will ask to log in. After this process, the app redirects to the home dashboard and not to the page the user desired to see before the login process.

# Steps to reproduce
1. Log in
2. Open a joined classroom
3. Open a new tab with the app and log out of it, close the opened tab
4. On the first tab, reload the page
5. Log in
6. The app will redirect to the home dashboard

# Environment
Operating System : MacOS 11.1
Browser : Safari
Login method : Github OAuth

**Comment by M4n0x** [comment]
fixed in #275
