### ISSUE TITLE
Connection to the website with GitHub not working

### ISSUE THREAD

**Issue by Psemata** [HE-Arc/Caravel#158]
Error 500 popping when i tried to connect with GitHub

**Comment by M4n0x** [comment]
Je viens de tester l'API GitHub semble OK, il faudrait tenter de supprimer les infos de sessions parfois suite à une mauvaise manipulation ça peut rendre la connexion impossible : pour tester simplement dans un premier temps il faudrait tenter de se connecter en étant navigation privée
