### ISSUE TITLE
Button to create issue hidden 

### ISSUE THREAD

**Issue by JorisMonnet** [HE-Arc/Caravel#162]
![Screenshot_20210401-150641](https://user-images.githubusercontent.com/71325809/113298250-eae11c00-92fb-11eb-8920-cabbca7f268e.jpg)

Quand on commente sur mobile, le bouton pour créer une issue passe derrière la zone de texte

**Comment by M4n0x** [comment]
C'est le bouton pour remonter une issue, à terme il ne va pas rester donc pas de problème ;-)

**Comment by M4n0x** [comment]
C'est le bouton qui permet de remonter une issue, il ne restera pas à terme donc pas de problème ;-)
