### ISSUE TITLE
Fix : user settings 

### ISSUE THREAD

**Issue by M4n0x** [HE-Arc/Caravel#70]
- Limiter la taille des images en entrée (si trop grande le site plante)
- Password strenght non fonctionnel
- le file name de la picture devrait être un hash (ça permet de garder une taille fixe dans le nom du fichier et éviter des problèmes lorsque les ids des users deviennent trop grand)

**Comment by M4n0x** [comment]
Je ré-ouvre les password strenght ne sont pas fonctionnels

**Comment by JorisMonnet** [comment]
corrigé
