### ISSUE TITLE
View : Weekly 

### ISSUE THREAD

**Issue by M4n0x** [HE-Arc/Caravel#8]
Weekly view, see the mockup page in wiki section for more details

**Comment by M4n0x** [comment]
Look for horizontal accordion ex. https://mdbootstrap.com/snippets/jquery/mdbootstrap/887993

(take care of mobile's users !)

**Comment by maximewel** [comment]
Note : The site is operational and the upcoming view already fullfills the core of the "weekly" views. As the deadline comes closer, this view is moved in the "feature++" category - nice-to-have, but certainly not a priority for the moment
