### ISSUE TITLE
Deploy : configurer authentification externe

### ISSUE THREAD

**Issue by M4n0x** [HE-Arc/Caravel#84]
Sur le serveur de déploiement configurer les infos pour la connexion avec Google et GitHub

(pas de branche nécessaire, configurer .env et ensuite fermer cette issue)

**Comment by JorisMonnet** [comment]
Problemes avec la connexion github -> tests en cours

**Comment by JorisMonnet** [comment]
Problème dans un nom de variable du .env -> corrigé
