### ISSUE TITLE
Test : Fix error on tasks (upcoming.blade.php)

### ISSUE THREAD

**Issue by maximewel** [HE-Arc/Caravel#94]
# Problem scenario
* Arrises when calling the "group/x/tasks" view
* Only arrises on certain group, not everyone

# screens
![image](https://user-images.githubusercontent.com/71388163/100023331-13548900-2de5-11eb-8b3c-ee244c278c19.png)
\
![image](https://user-images.githubusercontent.com/71388163/100023548-7514f300-2de5-11eb-832b-3f7089461e5f.png)

**Comment by M4n0x** [comment]
Je profite pour corrigé le resize des images dans le markdown et les types de fichiers qu'on peut pousser sur le srv
