### ISSUE TITLE
Bug : Oauth multi compte 

### ISSUE THREAD

**Issue by M4n0x** [HE-Arc/Caravel#99]
Lorsqu'on est loggué avec un compte google, on peut se délogguer mais le compte google utilisé précédemment est gardé dans les cookies. Si on a plusieurs comptes impossible de changer, il faut manuellement supprimer les cookies pour pouvoir changer de compte.

Il faudrait rajouter dans la proc de logout qqch pour que le compte google utilisé ne soit pas gardé.

**Comment by JorisMonnet** [comment]
Pour se connecter avec un autre compte il faut se deconnecter directement depuis google ou github, les cookies ne proviennent pas de caravel
